
caption ='四千單刷題機';

//每題有幾個選項
numberOfOptions = 4;

//每列最多可以有幾個選項
numberOfOptionsPerRow = 1;	

//每回合抽幾題題目
numberOfQuestionsPerRound = 50;

//出題時選擇題目的方式 true:亂數選題  false:按題庫順序
select_questions_in_random = true; 


//聲音檔路徑的前置網址
//也就是會為 questionLines 的左欄前面自動加上的字串
//
// English 1200
soundBaseURL = 'https://gsyan888.github.io/english1200/';

//是否使用 TTS 的語音
tts_enabled = true;

//----------------
//Google TTS 文字轉語音的設定
//----------------
tts_language = 'en';  // en : 英語,   zh_tw : 中文
tts_speed = 0.3;  //語音的速度 0 ~ 1 (可用小數)
tts_base_url = 'https://translate.google.com/translate_tts?ie=UTF-8&tl='+tts_language+'&client=tw-ob&ttsspeed='+tts_speed+'&q=';

//-------------------------------
//用來偵測換行字元用的測試區塊
//請勿更動
//並且放在題庫設定區塊之前
//-------------------------------
//測試區塊開始
CR_LF_test = function(){/*--這一行請勿更改--
CR_LF testing block
-----*/}.toString().slice("function(){/*--這一行請勿更改--".length+2,-9);
CR_LF_First_Pos = CR_LF_test.indexOf('_LF')-'CR_LF'.indexOf('_LF');
//測試區塊結束
//-------------------------------


//題庫
//欄位分隔符號為兩個井字號(##)
seperator = '##';

//左欄為聲音檔路徑
//右欄為中文
questionLines = function(){/*--這一行請勿更改--
abandon##v. 遺棄;中止
ability##n.能力;才能
able##adj.能;有能力的
aboard##prep./adv.在(船、飛機、車)上
about##prep./adv.關於
above##prep./adv./adj. 在...上面;優於,勝過
abroad##adv.在(到)國外
abrupt##adj.突然的;魯莽的
absence##n.缺席;缺少
absent##adj.缺席的
absolute##adj.完全的;絕對的
absorb##v.吸收;理解
abstract##adj.抽象的
academic##adj.學院的;學術的
accept##v./n.接受
acceptable##adj.可以接受的
acceptance##n.接受
accident##n.事故
accidental##adj.偶然的;意外的
accompany##v.陪同
accomplish##v.完成
account##n.帳戶;描述
account##v.認為;解釋
accountant##n.會計師
accuracy##n.正確(性)
accurate##adj.準確的
accuse##v.把...歸咎(於);指控
ache##n./v.疼痛
achieve(ment)##v.(n)完成;達到
acquaintance##n.熟人
acquire##v.取得
acquisition##n.取得;獲得物
acre##n.英畝
across##prep./adv.橫越
act##n./v.行動;表演
action##n.行動;作用
active##adj.活躍的;積極的
activity##n.活動;活動力
actor##n.男演員
actress##n.女演員
actual##adj.實際的
adapt##v.使適應
add##v.增加
addition##n.增加;附加
additional##adj.附加的
address##n./v.地址;致詞
adjust(ment)##v.(n.)調整
admirable##adj.令人欽佩的
admiration##n.欽佩
admire##v.欽佩;欣賞
admission##n.加入許可;承認
admit##v.承認
adopt##v.採取;收養
adult##n.成年人
advance##n./v.促進;將...提前
advanced##adj.先進的;高等的
advantage##n.有利條件;優勢
adventure##n.冒險
advertise(ment)##v.(n)為...做廣告
advice##n.勸告;消息
advise##v.勸告;忠告;通知
adviser/advisor##n.顧問
affair##n.事情;事件
affect##v.影響;使感動
afford##v.類得起;承擔得起
afraid##adj.害怕的
after##prep./adv./adj.在...之後;以後的
afternoon##n.下午
afterward(s)##adv.以後
again##adv.再一次
against##prep.反對;對著
age##n./v.年齡;使變老
agency##n.代理機構;仲介
agent##n.代理人;仲介人
aggressive##adj.好鬥的;積極的
ago##adv. 在~以前
agree(ment)##v.(n)同意
agriculture##n.農業
ahead##adv.在·前面;領先
aid##n./v.幫助
AIDS##n.愛滋病
aim##n./v.目標;瞄準
air##n.空氣;大氣;天空
aircraft##n.航空器;飛機
airline##n.航線;航空公司
airmail##n.航空郵件
airplane##n.飛機
airport##n.機場;航空站
alarm##n./v.警報;驚恐
album##n.一套唱片;相簿
alcohol##n.酒精
alert##adj./v./n.警覺的;警戒
alike##adj./adv. 相同的
alive##adj.活著的;有活力的
all##adj./adv./pron.全部的;全體
alley##n.小巷子;小徑
allow##v. 允許
almost##adv.幾乎
alone##adj./adv.單獨的
along##prep./adv.沿著;一起
aloud##adv.大聲地
alphabet##n.字母系統
already##adv.已經;先前
also##adv.同樣地
although##conj.雖然;然而
altogether##adv.完全;總而言之
always##adv.總是;永遠
amateur##n./adj.業餘從事者;業餘的
amaze(ment)##v.(n)使驚愕
ambassador##n.大使;使節
ambition##n.抱負;志向
ambitious##adj.野心勃勃的
ambulance##n.救護車
among##prep.在...之中
amount##n./v.共計;總數
amuse(ment)##v.(n.)給~提供娛樂
analysis##n.分析
analyze##分析
ancestor##n.祖先
ancient##adj.古代的
angel##n.天使
anger##n.生氣
angle##n 角度;立場
angry##adj.生氣的
animal##n.動物
ankle##n.足踝
anniversary##n.週年紀念
announce(ment)##v.(n.) 宣布
annual##adj.一年一度的
another##adj./pron.另一個
answer##n./v.答案
ant##n.螞蟻
anxiety##n.焦慮
anxious##adj.焦慮的
any##adj./adv./pron.任何的;若干
anyhow##adv.無論如何
anyway##adv.無論如何
apart##adj./adv.分開的
apartment##n.公寓大樓
ape##n.大猩猩
apologize##v.道歉
apology##n.道歉
apparent##adj.明顯的
appeal##n./v.吸引;呼籲
appear##v.出現;顯露
appearance##n.外貌;顯露
appetite##n.胃口;食慾
appliance##n.器具;裝備
applicant##n.申請人
application##n.應用;申請書
apply##v.應用;申請
appoint##v.任命;指派
appointment##n.約定;指派
appreciate##v.欣賞;感激
appreciation##n.欣賞;感謝
approach##n./v.接近;著手處理
appropriate##adj.適當的
approval##n.同意;認可
approve##v.同意;認可
April##n.四月
apron##n.圍裙;工作裙
arch##n.拱門;拱形
architect##n.建築師;設計師
architecture##n.建築學;建築風格
area##n.區域;範圍
argue(ment)##v.(n.)爭論;主張
arise##v.升起;復活
arithmetic##adj./n.算術的
arm##n.手臂
armchair##n.扶手椅
army##n.軍隊;團體
around##prep./adv.各處;大約
arouse##v.喚起
arrange(ment)##v.(n.) 安排
arrest##v./n.逮捕;拘留
arrival##n.到達;到達者
arrive##v.到達;抵達
arrow##n.箭
art##n.藝術;藝術品
article##n.文章;冠詞
artificial##adj.人造的
artist##n.藝術家;藝人
artistic##adj.藝術的
as##prep./adv./conj 如同;當...時;雖然
ash##n.灰燼;骨灰
ashamed##adj.感到羞恥的
aside##adv.在旁邊;除...之外
ask##v.詢問;要求
asleep##adj.睡著的
aspect##n.方面;觀點
assemble##v.集合
assembly##n.與會者;議會
assign(ment)##v.(n.) 指派
assist##v.協助
assistance##n.協助
assistant##n.助理
associate##v.關聯
association##n.協會;聯想;合作
assume##v.假定;假裝
assurance##n.保證
assure##v.保證
astronaut##n.太空人
athlete##n.運動員
athletic##adj.運動的
atmosphere##n.氣壓;氣氛
attach(ment)##v.(n.) 裝上;附加
attack##v./n.攻擊
attempt##v./n.嘗試
attend##v.參加
attention##n.注意力
attitude##n.態度
attract##v.吸引;引誘
attraction##n.吸引力
attractive##adj.有吸引力的
audience##n.觀眾;聽眾
August##n.八月
aunt##n.姑媽;阿姨
author##n.作者
authority##n.權力;當局
automatic##adj.自動的
automobile/auto##n.汽車
autumn##n.秋季
avenue##n.大道
average##adj./n./v.平均的
avoid##v.避免;躲開
await##v.等候;期待
awake##adj./v.清醒的;喚醒
awaken##v.意識到;使覺醒
award##v./n 授予;獎品
away##adv.離開;不在
awful##adj.糟透的
awkward##adj.笨拙的;棘手的
baby##n.嬰兒;寶貝
back##adj./adv./n./v. 後面的;背部;贊助
background##n.背景
backward(s)##adv.反方向地
bacon##n.燻豬肉;培根肉
bacteria##n.細菌
bad##adj.不好的;有害的
bag##n.袋子
baggage##n.行李;裝備
bait##n./v.誘餌;引誘
bake##v.烘;烤
bakery##n.麵包店
balance##n./v.平衡
balcony##n.陽臺;樓座
ball##n.球;球狀體
ballet##n.芭蕾舞
balloon##n.氣球
bamboo##n.竹子
banana##n.香蕉
band##n.帶子;樂團
bandage##n.繃帶
bank##(1)n.銀行
bank##(2)n./v.堤;堆積
bankrupt##adj./v./n.破產的
bar##n.棒;沙洲;酒吧
barbecue##n./v.烤肉
barber##n.理髮師
bare##adj.裸的;不加掩飾的
barely##adv.勉強地;露骨地
bargain##n./v.買賣;便宜貨
bark##n./v.吠叫;咆哮
bam##n.穀倉;牲口棚
barrel##n.大桶
barrier##n.障礙物;棚欄
base##n./v.基礎
baseball##n.棒球
basement##n.地下室
basic##adj.基本的
basin##n.臉盆;洗滌槽
basket##n.籃子;簍子
basketball##n.籃球
bat##n./v.球棒
bath##n.澡缸;沐浴
bathe##v.洗澡;沐浴
bathroom##n.浴室
battery##n.電池
battle##n./v.戰役
bay##n.海灣
beach##n.海灘
beam##n.樑;光束
bean##n.豆子
bear##n.熊;魯莽之人
bear##v.承受;忍受
beard##n.(下巴上的)鬍鬚
beast##n.野獸
beat##n./v.敲擊;打敗
beautiful##adj.美麗的
beauty##n.美人
because##conj.因為
become##v.變成
bed##n.床
bedroom##n.臥室
bee##n.蜜蜂
beef##n.牛肉
beer##n.啤酒
before##prep./adv./conj. 在...之前
beg##v.乞求;乞討
beggar##n.乞丐
begin##v.開始
beginner##n.初學者
behave##v.表現;行為舉止
behavior##n.行為
behind##prep./adv.在...後面;落後
being##n.存在;生物
belief##n.信念;信條
believe##v.相信
bell##n.鐘(聲);鈴(聲)
belly##n.腹部;胃
belong##v.歸屬於
below##prep./adv.在...下方
belt##n.腰帶;帶狀物
bench##n.長板凳
bend##n./v.彎曲
beneath##prep.在...下面
benefit##n./v.利益;有益於
berry##n.果
beside##prep.在旁邊
besides##prep./adv.除此之外
best##adj./adv.最好的
bet##n./v.打賭
better##adj./adv.更好的
between##prep./adv.介於...之間
beyond##prep./adv.在遠處
bicycle/bike##n.腳踏車
big##adj.大的
bill##n.帳單;鈔票
billion##n.十億;大量
bind##v.捆;綁
bingo##n.賓果遊戲
biography##n.傳記
biology##n.生物學
bird##n.鳥
birth##n.出生;分娩
biscuit##n.小麵包;餅乾
bite##n./v.一口之量;咬
bitter##adj.有苦味的;痛苦的
black##adj./n.黑的
blackboard##n.黑板
blame##n./v.責備;歸咎於...
blank##adj./n.空白的
blanket##n.毛毯
bleed##v.流血
blend##v.使混合
bless##v./n.為...祝福
blessing##n.賜福;同意
blind##adj./v.瞎的;使看不見
block##n./v.塊;障礙物;堵住
blood##n.血液
bloody##adj.血腥的
bloom##n./v.花;開花
blow##n./v.吹;吹氣;打擊
blue##adj./n.藍色的
blush##v./n.臉紅
board##n.木板;牌子
board##v.登上(船或車等)
boast##v.自吹自擂;誇耀
boat##n./v.小船;划船
body##n.身體;主要部分
boil##v./n.沸騰
bold##adj.英勇的;大膽的
bomb##n./v.炸彈;轟炸
bond##n.聯結;契約;債券
bone##n.骨頭;骨質
book##n.書籍
book##v.預訂;登記
bookcase##n.書架;書櫥
boot##n.(長筒)靴
border##n./v.邊界;比鄰
bore##n./v.使厭煩
bored##adj.感到厭煩的
boring##adj.令人厭煩的
born##adj.出生的
borrow##v.借入
boss##n.老闆
both##adj./adv./pron.兩者皆
bother##v./n.打擾;煩惱
bottle##n./v.瓶子;把...裝瓶
bounce##n./v.跳,躍;使反彈
bow##(1) n.弓;虹;蝴蝶結
bow##(2) v.拉彎;彎曲;鞠躬
bowl##n.碗
bowling##n.保齡球
box##n./v.箱,盒;把...裝箱
boy##n.男孩;少年
brain##n.腦袋;智力
brake##n./v.煞車
branch##n./v.樹枝;分支
brand##n.商標;烙印
brave##adj.勇敢的
bravery##n.勇敢;勇氣
bread##n.麵包
break##n./v.打破;破曉
breakfast##n./v.早餐
breast##n.胸部
breath##n.呼吸
breathe##v.呼吸
breed##n./v.繁衍;滋生
breeze##n./v.微風;和風
brick##n.磚
bride##n.新娘子
bridge##n./v.橋樑;艦橋
brief##adj./n./v.簡短的
bright##adj.明亮的;聰明的
brilliant##adj.光輝的;傑出的
bring##v.帶來;引起
broad##adj.寬廣的;概括的
broadcast##n./v.廣播;播放
brook##n.小河
brother##n.兄弟
brown##adj./n.棕色的
brush##n./v.刷子;刷
brutal##adj.殘忍的
bubble##n.氣泡;泡影
buck/dollar##n.(美)元
bucket##n.水桶;桶狀物
bud##n./v.芽;發芽
budget##n./v.預算
buffet##n.自助餐;快餐
bug##n.蟲子
build##v.建造
building##n.建築物
bull##n.(未閹割的) 公牛
bullet##n.子彈
bulletin##n.公報;新聞快報
bump##v./n.碰;重擊
bunch##n.一束;一群
bundle##n.捆;包裹
burden##n./v.負擔;加負擔於...
bureau##n.局;處;署
burn##v./n.燃燒;燒傷
burst##v./n.爆發;爆炸
bury##v.埋
bus##n.巴士
bush##n.灌木叢
business##n.商業;交易
busy##adj./v.忙碌的
butter##n./v.奶油;塗奶油於
butterfly##n.蝴蝶
button##n./v.鈕扣;按鈕
buy##v.買
cab##n.計程車
cabbage##n.甘藍菜
cabin##n.客艙
cabinet##n.櫥櫃;密室
cable##n./v.電纜;有線電視
cafe##n.咖啡店;咖啡
cafeteria##n.自助餐館
cage##n./v.籠子;監牢
cake##n.蛋糕
calculate##v.計算
calculation##n.計算
calculator##n.計算機
calendar##n.日曆;行事曆
call##n./v. 呼叫;打電話
calm##adj./v. 鎮靜的
camel##n.駱駝
camera##n.照相機
camp##n./v.營地;露營
campaign##n./v.競選活動;戰役
campus##n.(大學的) 校園
can##n./v.罐頭;金屬容器
cancel##v.取消
cancer##n.惡性腫瘤;癌症
candidate##n.候選人
candle##n.蠟燭
candy##n.糖果
cane##n.藤條;甘蔗
canvas##n 帆布
canyon##n.峽谷
cap##n./v.帽子;覆蓋
capable##adj.有能力的
capacity##n.容量;能力
cape##n 披肩;海角
capital##adj./n.主要的;首都;資本
capital(ism)##n.資本主義(制度)
captain##n.隊長;船(艦)長
capture##v./n.捕獲;獲物
card##n.卡片;紙牌遊戲
care##n./v.關心;照顧
career##n.職業
careful##adj.仔細的
careless##adj.粗心大意的
cargo##n.貨物
carpenter##n.木匠
carpet##n.地毯
carriage##n.四輪馬車;運輸
carrier##n.運送人;航空母艦
carrot##n.胡蘿蔔
carry##v.運送;攜帶
cart##n./v.貨車;載運
cartoon##n.卡通;連環漫畫
carve##v.雕刻;開拓
case##(1) n.事實;實例
case##(2) n./v.容器;把...裝入箱中
cash##n./v.現金
cassette##n.卡式磁帶
cast##n./v.投;演員陣容
castle##n.城堡
casual##adj.偶然的;碰巧的
catch##v./n.抓住;捕獲
cattle##n.牛;牲口
cause##n./v.導致;原因
cave##n.洞穴
cease##v.停止
ceiling##n.天花板
celebrate##v.慶祝
celebration##n 慶祝
cell##n.小囚房;細胞
cent##n.一分錢
center##n./v.使集中;核心
central##adj.中央的;核心的
century##n.世紀
cereal##n.玉蜀黍薄片
ceremony##n.典禮;禮儀
certain##adj.確信的
chain##n./v.鏈條;束縛
chair##n.椅子
chalk##n.白堊;粉筆
challenge##n./v.挑戰
chamber##n.房間;室
champion##n.優勝者;戰士
championship##n.冠軍稱號;錦標賽
chance##n./v.偶然;機會
channel##n./v.海峽;溝渠
chapter##n.章,回
character##n.性格;特質
characteristic##adj./n.特有的;特性
charge##n./v.索價;控告
charm##nJv.魅力;使陶醉
charming##adj.有魅力的
chart##n./v.圖表
chase##v./n.追逐
chat##v./n.聊天
cheap##adj.便宜的
cheat##v./n.作弊;欺騙
check##n./v.支票;檢查
cheek##n.臉頰
cheer##n./v.歡呼;激勵
cheerful##adj.興高采烈的
cheese##n.乳酪;乾酪
chemical##adj./n.化學的
chemistry##n.化學;化學作用
cherish##v.珍惜
cherry##n.櫻桃
chess##n.西洋棋
chest##n.胸膛;箱子
chew##v./n.咀嚼;深思
chick##n.小雞;少婦
chicken##n.雞肉;膽小鬼
chief##adj./n.主要的;首領
child##n.小孩子
childhood##n.童年時期
childish##adj.孩子氣的
children##n. [pl.]小孩子
chilly##adj. 冷颼颼的
chimney##n.煙囪
chin##n.下巴
china##n.瓷器
chip##n./v.晶片;削
chocolate##n.巧克力
choice##n./adj.選擇
choke##v./n.窒息;阻塞
choose##v.選擇
chop##v./n.劈;肋排肉
chopstick(s)##n.筷子
chorus##n.合唱隊
church##n.教堂
cigarette##n.香煙;煙捲
circle##n./v.循環;畫圓圈
circulate##v.循環;流通
circulation##n.循環;流通;貨幣
circumstance##n.情況;詳情
circus##n.馬戲團
citizen'##n.公民;市民
city##n.城市
civilization##n.文明
claim##n./v.要求;聲稱
clarify##v.澄清
clash##n./v.衝突;發出鏗鏘聲
class##n./v.階級;班級
classic##adj./n.經典的;名著
classical##adj.極好的;古典的
claw##n.爪子;鉗;贅
clay##n.黏土;泥土
clean##adj./adv./v.乾淨的
clear##adj./v.清楚的
clerk##n.店員
clever##adj.伶俐的;機敏的
client##n.客戶
cliff##n.懸崖
climate##n.氣候;風氣
climax##n.高潮
climb##v.攀爬
clock##n.時鐘
close##adj./adv.接近的
close##v.關上;結束
closet##n.壁櫥;衣櫥
cloth##n.布料;衣料
clothe##v.為...穿衣
clothes##n.衣服
clothing##n.衣服;覆蓋物
cloud##n./v.雲;遮蔽
cloudy##adj.多雲的
clown##n.小丑
club##n./v.俱樂部;募集
clue##n.線索
clumsy##adj.笨拙的
coach##n./v.教練員;公車
coal##n.煤礦;煤塊
coarse##adj.粗糙的
coast##n.海岸;沿海地區
coat##n./v.外套;覆蓋
cockroach##n.蟑蚣卜;油蟲
cocktail##n.雞尾酒
coconut##n.椰子
code##n./v.密碼;法典
coffee##n.咖啡
coin##n.硬幣
coke##n.可口可樂
collapse##v./n.崩塌
collar##n.衣領;項圈
collect##收集;收藏
collection##n.收藏品;收集
college##n.大學;學院
colony##n.殖民地
color##n./v.顏色;彩色
colorful##adj.多采多姿的
column##n.欄;圓柱
comb##n./v.梳子;梳頭
combination##n.聯合(體)
combine##v.結合
come##v.來到;甦醒
comedy##n.喜劇
command##n./v.命令;控制
commander##n.指揮者
comment##n./v.評論
commerce##n 商業;交易
commercial##adj./n.商業的
commission##n./v.佣金;委託
commit##v.犯(罪);把...託交給...
commitment##n.承諾
committee##n.委員會
common##adj./n.一般的
communicate##v.溝通
communication##n.溝通;訊息
community##n.社區;共同體
companion##n.夥伴;伴侶
company##n.公司;同伴
compare##v.比較
comparison##n.比較;對照
compete##v.競爭;比賽
competition##n.競賽;競爭
competitive##adj.競爭的
competitor##n.競爭者
complain##v.抱怨
complaint##n.抱怨
complete##adj./v.完全的;完成
complex##adj./n.複雜的;情結
complicate##v.使複雜化
complicated##adj.複雜的
compliment##n./v.讚美;祝賀
component##n.零件;成分
compose##v.作曲;組成
composer##n.作曲家;調停者
composition##n.作文;合成物
compute##v.估算;推算
computer##n.電腦
concentrate##v.專心
concentration##n 專心;集中
concern##n./v.關心;涉及
concert##n.演奏會;音樂會
conclude##v.結束;斷定
conclusion##n.結論;推論
concrete##adj./n.具體的;混凝土
condition##n./v.情況;決定
conductor##n.領導者;指揮
conference##n.會議
confess##v.坦承
confidence##n.信心;自信
confident##adj.有自信的
confine##v.限制;使侷限
conflict##n./v.衝突
confront##v.面臨;對抗
confrontation##n.對質;對抗
confuse##v.把...弄糊塗;攪亂
confusion##n.混亂;困惑
congratulate##v.恭喜
congratulation##n.恭喜
congress##n.正式大會;立法機關
connect##v.連結
connection##n.連接;關聯
conquer##v.戰勝
conscious##adj.神智清醒的
consciously##adv.有意地
consciousness##n.意識;察覺
consent##n./v.同意
consequence##n.結果;重要性
consequent##adj.因...的結果而起的
conservative##adj.保守的
consider##v.認為;考慮
considerable##adj.值得考慮的
considerate##adj.設想周到的
consideration##n.考慮;動機
consist##v.組成;存在於...
consistent##adj.一致的
constant##adj.固定的
constitute##v.構成;制定
constitution##n.憲法;法規
construct##v.建造
construction##n.建造物;建設
constructive##adj.建設性的
consult##v.與...商量
consultant##n.顧問;諮詢者
consume##v.消耗;花費
consumer##n.消費者
contact##n./v.接觸;聯繫
contain##v.包含
container##n.容器
contend##v.競爭;鬥爭
content##adj./v.滿足的
content(s)##n.內容
context##n.上下文
continent##n.大陸;大洲
continental##adj.洲的;大陸的
continual##adj.不間斷的
continue##v.持續
continuous##adj.連續的
contract##n./v.契約
contrary##adj./n.相反的
contrast##n./v.對比
contribute##v.捐獻;貢獻
contribution##n.貢獻;捐獻
control##n./v.控制
convenience##n.便利設施;方便
convenient##adj.便利的
convention##n.慣例;會議
conventional##adj.慣例的;協定上的
conversation##n.會話;談吐
converse##v.談話
convert##v.轉換
convey##v.運輸;傳遞
convince##v.說服
cook##n./v.廚師;烹煮
cooker##n.炊具
cookie/cooky##n.甜餅乾
cool##adj./v.涼爽的;使冷卻
cooperate##v.合作
cooperation##n.合作
cooperative##adj.合作的
cope##v.競爭;妥善處理
copy##n./v.副本;拷貝
cord##n.細繩;粗線
corn##n.玉米;穀物
comer##n.角落
correct##adj./v.正確的;更正
correspond##v.符合;通信
cost##n./v.花費;付出
costly##adj.貴重的;代價高的
costume##n.服裝;戲服
cottage##n.農舍;小屋
cotton##n.棉
couch##n.長沙發;睡椅
cough##v.咳嗽
council##n.會議
count##n./v.計算
counter##n.櫃檯;籌碼
counter##adj./adv./n./v.相反的;反擊
country##n.國家;鄉下
countryside##n.鄉村
county##n.郡;縣
couple##n.(一)對
courage##n.勇氣
courageous##adj.勇敢的
course##n.課程;過程
court##n.法庭
cousin##n.表(兄弟姊妹)
cover##n./v.封面;遮蓋
cow##n.母牛
coward##adj./n.懦弱的;懦夫
cowboy##n.牛仔;牧牛人
crack##n./v.爆烈聲;裂開
cradle##n./v.搖籃;撫育
craft##n.工藝;太空船
crash##n./v.墜毀;撞擊
crawl##v.爬行;蠕動
crayon##n.蠟筆
crazy##adj.瘋狂的
cream##n.奶油;乳脂
create##v.創造
creation##n.創作;萬物
creative##adj. 有創造力的
creature##n.生物
credit##n./v.信用;賒帳
creep##v.躡手躡腳地走
crew##n.(一群)工作人員
cricket##n.蟋蟀
crime##n.罪行;犯罪活動
criminal##adj/n.犯罪的;罪犯
crisis##n.危機
critic##n.評論家
critical##adj.關鍵性的;批判的
criticism##n.評論
criticize##v.批評
crop##n.作物
cross##n./v.交叉;越過
crowd##n./v.人群;擠滿
crowded##adj.擁擠的
crown##n./v.王冠;為...加冕
cruel##adj.殘酷的
crush##v./n.弄碎;壓碎
cry##v./n.哭;叫喊
crystal##adj./n.水晶的
cultivate##v.耕作;培養
cultural##adj.文化的;教養的
culture##n.文化;教養
cunning##adj.狡猾的;奸詐的
cup##nJv.杯子
cupboard##n.碗櫃
cure##n/v.治療;治癒
curiosity##n.好奇心
curious##adj.好奇的
current##adj./n.目前的;潮流
curtain##n./v.簾;給...裝上簾子
curve##n./v 曲線;使彎曲
cushion##n.墊子
custom##n.海關;習慣
customer##n.顧客
cut##n./v.切
cute##adj.可愛的
cycle##n./v.週期;循環
daddy/dad##n.爹地
daily##adj./adv.每日的
dairy##n.乳品店
dam##n./v.水壩;築壩於...
damage##n./v.損害;毀壞
dance##n./v.舞蹈
dancer##n.舞者
danger##n.危險
dangerous##adj.危險的
dare##v.敢於...;膽敢
dark##adj./n.黑暗的
darling##adj./n.親愛的
date##n.棗;棗椰樹
date##n./v.日期;約會
daughter##n.女兒
dawn##n./v.黎明;破曉
day##n 白天
daydream##n./v.白日夢
dead##adj.死去的;無效的
deadline##n.截止期限
deaf##adj.聾的
deal##n ./v.交易;處理
dear##adj./n./adv.親愛的
debate##n./v.爭論
debt##n.債
deceive##v.欺騙
December##n.十二月
decide##v.決定
decision##n.決定
deck##n.甲板
declaration##n.宣布;聲明
declare##v.宣告;聲明
decline##n./v.下降
decorate##v.裝飾
decoration##n.裝飾;裝溝
decrease##v./n.減少
deed##n.行為;功績
deep##adj./adv.深的
deer##n.鹿
defeat##n./v.失敗;擊敗
defend##v.防守;防衛
defense##n.防衛
defensive##adj.防護的;保衛的
define##v.解釋;給...下定義
definite##adj.明確的;肯定的
degree##n.度數;學位;等級
delay##n./v.拖延
delicate##adj.纖弱的;雅緻的
delicious##adj.美味可口的
delight##n./v.喻快
delightful##adj.令人愉快的
deliver##v.遞送
delivery##n.投遞;交貨
demand##n./v.請求;要求
demanding##adj.苛責的
democracy##n.民主
democratic##adj.民主的
demonstrate##v.證明;展示;遊行
demonstration##n.驗證;示威運動
denote##v.意味著
dense##adj.密集的;稠密的
dental##adj./n. 牙齒的;齒音(的)
dentist##n.牙科醫師
deny##v.否定;否認
depart##v.分離;啟程
department##n 部門;系
departure##n.分離;啟程
depend##v.依賴
dependent##adj.依賴性強的
deposit##n./v.存款;押金;放置
depress##v.使沮喪
depression##n.沮喪
depth##n.深度
describe##v.描述
description##n.描寫;說明?
desert##n.沙漠
desert##v.拋棄
deserve##v.應得
design##n./v.設計
designer##n.設計師
desire##n./v.慾望
desk##n.書桌
desperate##adj.絕望的
despite##prep.儘管
dessert##n.甜點;餐後點心
destination##n.目的地
destroy##v.摧毀
destruction##n.破壞
destructive##adj.毀滅性的
detail##n./v.細節
detailed##adj.詳細的
detect##偵測到
detergent##n.洗潔劑
determination##n.決心
determine##v.決定;堅決
develop(ment)##v.(n.)發展
device##n.裝置
devil##n.魔鬼
devise##v.策劃
devote##v.將...奉獻給
devoted##adj.專心致志的
devotion##n.奉獻
dial##v./n.撥號;刻度盤
dialogue##n.對話
diamond##n.鑽石
diary##n.日記
dictionary##n.字典
die##v.死亡
diet##n.飲食;特種飲食
differ##v.不同於...
difference##n.差異
different##adj.不同的
difficult##adj.困難的
difficulty##n.困難
dig##v. 挖;掘
digest##v.消化
digestion##n.消化作用
dignity##n.尊嚴
dilemma##n.困境
diligence##n.勤勉
diligent##adj.勤奮的
dim##adj.朦朧的
dime##n.一角硬幣
dimension##n.尺寸;範圍
diminish##v.減少
dine##v.用餐
dinner##n.晚餐
dinosaur##n.恐龍
dip##v.浸;泡
diploma##n.學位證書
diplomat##n.外交官
direct##adj./v.直接的;指向
direction##n.方向
director##n.主管;導演
dirt##n.污物;泥土
dirty##adj.污穢的
disability##n.無能
disable##v.使失去能力
disadvantage##n.不利之條件
disagree(ment)##v.(n)不同意
disappear##v.消失
disappoint(ment)##v.(n)使失望
disaster##n.災難
disastrous##adj.多災多難的
disc/disk##n.圓盤;唱片
discard##v.摒棄
discipline##n.紀律
disco##n.迪斯可舞廳/音樂
disconnect##v.使分離
discount##n./v.折扣
discourage(ment)##v.(n)使洩氣;使沮喪
discover##v.發現
discovery##n.發現
discrimination##n.歧視;區別
discuss##v.討論
discussion##n.討論
disease##n.疾病
disguise##n./v.偽裝
dish##n.碟;菜餚
dishonest##adj.不誠實的
dislike##不喜歡
dismiss##v.解散
disorder##n./v.使混亂;騷亂
disorganized##adj.雜亂無章的
dispatch##v.派遣;發送
disperse##v.使散開
display##n./v.陳列
displease##v.使不快
stocking(s)##n.長襪
stomach##n.胃
stone##n./v.石頭
stool##n.凳子
stop##n./v.車站;停止
store##n./v.店鋪;儲存
storm##n./v.暴風雨;猛烈攻擊
stormy##adj.有暴風雨的
story##n.故事
stove##n.火爐
straight##adj./adv.筆直的
strange##adj.奇怪的
stranger##n.陌生人
strategy##n.策略
straw##n.稻草;麥桿
strawberry##n.草莓
stream##n./v.小河
street##n.街道
strength##n.力氣
strengthen##v.加強
stress##n./v.壓力
stretch##n./v.伸展
strict##adj.嚴格的
strike##n./v.罷工;猛然攻擊
string##n./v.細繩
strive##v.奮鬥
stroke##n.一擊
stroke##v.撫摸
strong##adj.強壯的
structure##n.結構
struggle##n./v.掙扎;努力
stubborn##adj.固執的
student##n.學生
studio##n.工作室
study##n.學業
stu##勿 v.學習
stuff##n.材料
stuff##v.填滿
stupid##adj.愚蠢的
style##n.風格
subject##n.主題
submarine##n.潛水艇
substance##n.物質
subtract##v.減掉
suburb##n.郊區
succeed##v.達成
success##n.成功
successful##adj.成功的
such##adj./prop.如此的
suck##v.吸;吮
sudden##adj.突然的
suffer##v.遭受
sufficient##adj.充足的
sugar##n.糖
suggest##v.建議
suggestion##n.提議
suicide##n.自殺
suit##n.一套衣服
suit##v.適合
suitable##adj.合適的
sum##n.總數
summarize##v.概述;總結
summary##n.摘要
summer##n.夏天
summit##n.山頂
sun##n./v.太陽;曬太陽
Sunday##n.星期日
sunny##adj.陽光充足的
super##adj.極好的
superior##adj.上等的
supper##n.晚餐
supply##n./v.供應
support##n./v.支持
suppose##v.猜想
sure##adj.確信的
surface##n.表面
surgeon##n.外科醫師
surgery##n.外科(手術)
surprise##n./v.驚訝;使驚奇
surprised##adj.感到驚奇的
surprising##adj.使人驚訝的
surround##v.圍繞
surroundings##n.環境
survey##n./v.調查;審視
survival##n.殘存
survive##v.悻存
suspicion##n.懷疑
suspicious##adj.猜疑的
swallow##n.燕子
swallow##v.吞下
swan##n.天鵝
swear##v.發誓
sweat##n./v.汗水;出汗
sweater##n.毛線衫
sweep##n. v.清掃;打掃
sweet##adj.甜的
sweet(s)##n.糖果;甜點
swim##n. v.游泳
swing##n./v.鞦韆;搖擺
switch##n./ v.開關;轉變
sword##n.劍
syllable##n.音節
symbol##n.象徵
sympathetic##adj.有同情心的
sympathize##v.同情
sympathy##n.同情心
symphony##n.交響樂
system##n.系統
systematic##adj.有系統的
table##n.桌子
tail##n.尾巴
tailor##n.裁縫師
take##v.拿(走)
tale##n.故事
talent##n.天賦
tally##n./v.聊天;說話
tall##adj.高的
tank##n.大容器
tap##n./v.塞子;輕敲
tape##n./v.錄音帶
target##n./v.靶子;對·瞄準
task##n.任務
taste##n./v.味覺;品嚐
tasty##adj.美味的
tax##n./v.稅;對...微稅
taxi##n.計程車
tea##n.茶
teach##v.教導
teacher##n.教師
team##n.隊
tear(s)##(1)n.眼淚
tear##(2)v.撕破
tease##v.戲弄;取笑
technical##adj.技術性的
technician##n.技術人員
technique##n.技術
technological##adj.工業技術的;科技的
technology##n.工業技術;(一門)科技
teenager##n.青少年
telegram##n.電報
telegraph##n.電報
telephone##n.電話
telescope##n.望遠鏡
television##n.電視機
tell##v.告訴
temper##n.脾氣
temperature##n.溫度
temple##n.廟宇
temporary##adj.暫時的
ten##n.十
tend##v.有...的傾向
tendency##n.癖好
tender##adj.嫩的
tennis##n.網球(運動)
tense##adj.緊張的
tension##n.緊張
tent##n 帳篷
tern##n.期限
terrible##adj.可怕的
terrific##adj.極好的;嚇人的
terrified##adj.嚇壞了的
terrify##v.使驚恐
territory##n.領土
test##n./v. 小考;考驗
text##n.本文
textbook##n.教科書
than##prep./conj.比;比較
thank##n./v.感謝
thankful##adj.感謝的
theater##n.戲院
theme##n.主題
theory##n.理論
there##n/adv.那裡
therefore##adv.因此
these##adj./pron.這些
thick##adj.厚的
thief##n.小偷
thin##adj.薄的
thing##n.束西
think##v.想
third##adj./n.第三
thirst##n.口渴
thirsty##adj.口渴的
thirteen##adj./n.十三
thirty##adj./n.三十
thorough##adj.徹底的
those##adj./pron.那些
though##adv./conj.然而;雖然
thought##n.思想
thoughtful##adj.體貼的;沉思的
thousand##adj./n.一千
thread##n./v.線;穿線於
threat##n.威脅
threaten##v.恐嚇
three##adj./n.三
throat##n.喉嚨
through##prep./adv.通過
throughout##prep./adv.遍及
throw##v.投;扔
thumb##n./v.拇指
thunder##n./v.雷聲;打雷
Thursday##n.星期四
thus##adv.這樣
ticket##n.票
tide##n.潮汐
tidy##adj.整潔的
tie##n.領帶
tie##v.繫;捆
tiger##n.老虎
tight##adj./adj.緊的;緊緊地
tighten##v.(使)繃緊
till##prep./conj.直到
timber##n.木材
time##n./v.時間
timid##adj.膽小的
tiny##adj.非常小的
tip##n./v.小費
tire##n.輪胎
tire##v.疲勞
tired##adj.疲倦的
tiresome##adj.令人厭煩的
tissue##n.組織
title##n.標題
toast##n./v.吐司;烤;烘
tobacco##n.煙草
today##adv./n.今天
toe##n.腳趾
tofu##n.豆腐
together##adv.一起
toilet##n.洗手間;廁所
tolerate##v.容忍
tomato##n.蕃茄
tomb##n.墳
tomorrow##adv./n.明天
ton##n.噸
tone##n.音調
tongue##n.舌(頭)
tonight##adv./n.今晚
tool##n.工具
tooth##n.牙齒
toothpaste##n.牙膏
top##adj./nJv.頂端的;頂部
topic##n.題目
tortoise##n.(陸)龜
toss##n./v.扔;擲
total##adj./n./v.完全的;總數
touch##n./v.觸覺;觸摸
tough##adj.堅韌的
tour##n./v.旅遊
tourism##n.觀光業
tourist##n.觀光客
toward(s)##prep.向
towel##n.毛巾
tower##n./v.塔樓;屹立
town##n.城鎮
toy##n./v.玩具;玩弄
trace##n./v.蹤跡;追溯
track##n./v.軌道;追蹤
trade##n./v.貿易
tradition##n.傳統
traditional##adj.傳統的
traffic##n.交通
tragedy##n.悲劇
tragic##adj.悲慘的
train##n.火車
train##v.訓練
transfer##n./v.調動
translate##v.翻譯
translation##n.翻譯
translator##n.翻譯者
travel##n./v.旅行
traveler##n.旅行者
tray##n.盤子
treasure##n./v.金銀財寶;珍惜
treat##n./v.請客;對待
tree##n.樹
tremble##n./v.發抖
tremendous##adj.極大的
trend##n.趨勢
trial##n.審判
triangle##n.三角形
tribe##n.部落
trick##n./v.詭計;欺騙
tricky##adj.狡猾的
trip##n.旅行
triumph##n./v.勝利;戰勝
troop##n.部隊
tropical##adj.熱帶的
trouble##n./v.憂慮
troublesome##adj.令人討厭的
trousers##n.褲子
truck##n./v.卡車;用卡車裝運
TRUE##adj.真實的
trumpet##n./v.喇叭;鼓吹
trunk##n.樹幹
trust##n./v.信任
truth##n.事實
try##n./v.嘗試
tub##n 浴缸;盆
tube##n.管子
Tuesday##n.星期 v.
tune##n./v.曲調
tunnel##n.隧道
turkey##n.火雞
turn##n./v.轉動
turtle##n.(海)龜
twelve##adj./n.十二
twenty##adj./n.二十
twice##adv.兩次
twin##n.孿生子之一
twinkle##n./v.閃爍
twist##n./v.彎曲;扭曲
two##adj./n.二
type##n.類型
type##v.打字
typewriter##n 打字機
typhoon##n.颱風
typical##adj.典型的
typist##n.打字員
ugly##adj.醜陋的
umbrella##n.雨傘
uncle##n.伯父
under##prep./adv.在...下面
underwear##n.內衣
uniform##adj./n.相同的;制服
union##n.結合
unit##n.單位
unite##v.合併
unity##n.統一
universe##n.宇宙
university##n.大學
unless##conj.除非
unlike##prep.不像
until##prep./conj.直到...時
up##prep./adv.向上地
upper##adj.較高的
upset##adj./v.心煩的;使生氣
upstairs##adj.在樓上
urban##adj.城市的
urge##n./v.衝動;催促
urgent##adj.緊急的
us##pron.我們
usage##n.使用方法
use##n./v.益處;使用
used##adj.舊的
useful##adj.有用的
useless##adj.無用的
usual##adj.通常的
vacant##adj.空的
vacation##n.假期
vain##adj./n.無效的
valley##n.山谷
valuable##adj.珍貴的
value##n./v.價值;估價
vanish##v.消失
variety##n 多樣化
various##adj.各式各樣的
vary##v.變化
vase##n.花瓶
vast##adj.廣闊的
vegetable##n.蔬菜
vegetarian##adj./n.素食者
vehicle##n.車輛
verb##n.動詞
verse##n.詩節
very##adv.非常
victim##n.受害者
victory##n.勝利
video##n.錄影帶
view##n./v.景色;看
village##n.村莊
violate##v.違背;侵犯
violence##n.暴力
violent##adj.兇暴的
violet##adj./n.紫羅蘭
violin##n.小提琴
virus##n.病毒
visible##adj.看得見的
vision##n.視力
visit##n./v.探望
visitor##n.探訪者
visual##adj.視覺的
vital##adj.維持生命所必需的
vitamin##n.維他命
vivid##adj 生動的
vocabulary##n.詞彙
voice##n./v.聲音;表達
volleyball##n.排球
volume##n.音量
voluntary##adj.自願的
volunteer##n./v.志願者;自願
vote##n./v.投票
voter##n.選民
vowel##n.母音
voyage##n.航行
wagon##n.四輪運貨馬車
waist##n.腰
wait##n./v.等候
waiter##n.侍者
waitress##n.女侍
wake##v.醒來
waken##v.弄醒
walk##n./v.走
wall##n.牆
wallet##n.皮夾子
wander##v.徘徊(於)
want##n./v. 想要
warn##v.警告
warning##n.警告
wash##n./v.洗滌
waste##n./v.浪費
watch##n.手錶
watch##v.觀看
water##n./v.水
waterfall##n.瀑布
watermelon##n.西瓜
wave##n/v.波;揮動
way##n.路
weak##adj.虛弱的
wealth##n.財富
wealthy##adj.富裕的
weapon##n.武器
wear##n./v.穿;戴
weather##n.天氣
weave##v.紡織
web##n.網
wedding##n.婚禮
Wednesday##n.星期三
week##n.週
weekly##adj./adv.一週一次的
weekday(s)##n.工作日
weekend##n.週末
weep##v.哭泣
weigh##v.稱...的重量
weight##n.重量
welcome##n./v.歡迎
welfare##n.福利
well##adv.很好地
well##n.水井
West##adj./adv./n.西方的
western##adj./n.西方世界
wet##adj.溼的
whale##n.鯨
what##pron./conj.什麼
whatever##adj./advJpron./conj. 任何的;無論什麼
wheat##n.小麥
wheel##n./v.輪子;旋轉
when##pron./adv./conj. 那時;什麼時候
whenever##adv./conj.無論什麼時候;每當
where##adv./pron./conj. 在哪裡;哪裡
wherever##conj./adv.無論到哪裡
whether##conj.是否
which##pron.哪一個
while##conj/n.當...的時候
whisper##n./v.低語
whistle##n./v.哨子;吹口哨
white##adj./n.白色的
who##pron.誰
whoever##pron.無論是誰
whole##adj./n.全部的
whom##pron.誰
whose##pron.誰的
why##adv./pron./conj. 為什麼
wicked##adj.邪惡的
wide##adj.寬的
widen##v.(使)變寬
width##n.寬度
wife##n.妻子
wild##adj.野生的
will##(1) n.意志力
will##(2) v.將
willing##adj.願意的
win##n./v.勝利;獲勝
wind##(1)n.風
wind##(2) v.搖動
window##n.窗
windy##adj.多風的
wine##n./v.葡萄酒
wing##n./v.翅膀;飛行
winner##n.獲勝者
winter##n.冬天
wipe##v.擦v
wire##n./v.金屬線
wisdom##n.智慧
wise##adj.聰明的
wish##n./v.希望
witch##n.女巫
with##prep.與
within##prep./adv.在...之內
without##prep./adv.沒有
witness##n./v.目擊者
wolf##n.狼
woman##n.女人
wonder##n./v.想要知道
wonderful##adj.極好的
wood(s)##n.樹林
wool##n.羊毛
word##n.字
work##n./v.工作
worker##n.工人
world##n.世界
worm##n.蟲
worried##adj.煩惱的
worry##n./v.煩惱
worse##adj./adv.更壞的
worth##adj./n.價值
worthy##adj.值得...的
wound##n./v.傷口;使受傷
wrap##n./v.圍巾;包裹
wrist##n.腕
write##v.寫
writer##n.作家
writing##n.作品
wrong##adj./adv./n./v. 錯誤的
yard##n.碼
yawn##n./v.打呵欠
yeah##adv.對
year##n.年
yearly##adj./adv.每年一次
yell##v.喊叫
yellow##adj./n.黃色的
yesterday##adv./n.昨天
yet##conj./adv.但是;還
youngster##n.年輕人
youth##n.青春
youthful##adj.年輕的
zero##n.零
zone##n.地帶
zoo##n.動物園
-----*/}.toString().slice("function(){/*--這一行請勿更改--".length+2+(typeof(CR_LF_First_Pos)!='undefined' ? CR_LF_First_Pos:0),-9);
